(()=>{
  const zh=()=>lang==='zh';
  const st=()=>window.STUDIO_CRUD||{students:[],lesson_plans:[],content_items:[]};
  const sname=id=>st().students.find(s=>s.id===id)?.name||'—';
  const status=(entity,s)=>{const m={students:{active:['学习中','Active'],paused:['暂停','Paused'],completed:['已完成','Completed']},lesson_plans:{planned:['计划中','Planned'],ready:['已备好','Ready'],completed:['已完成','Completed'],archived:['已归档','Archived']},content_items:{idea:['灵感','Idea'],draft:['草稿','Draft'],ready:['待发布','Ready'],published:['已发布','Published']}};return m[entity]?.[s]?.[zh()?0:1]||s||''};
  function students(){return `<div class="crud-toolbar"><div><div class="eyebrow cyan">${zh()?'学生数据库':'STUDENT DATABASE'}</div><h2>${zh()?'学生管理':'Student Management'}</h2><p class="subtle">${zh()?'查看、创建、编辑或删除学生。每个学生的课程、备课与家长档案都以这个实体为中心。':'View, create, edit or delete students. Courses, prep and parent records are organized around each student.'}</p></div><button class="primary" onclick="openStudentForm()">＋ ${zh()?'新增学生':'Add student'}</button></div><div class="crud-list">${st().students.map(s=>`<article class="crud-card"><div class="crud-card-top"><div class="crud-student-header"><div class="digital-avatar"><div class="avatar-core">${esc((s.name||'?').slice(0,2).toUpperCase())}</div></div><div><span class="crud-status">${status('students',s.status)}</span><h3>${esc(s.name)}</h3><p>${esc(s.current_project||'')}</p></div></div><div class="crud-actions"><button class="crud-btn" onclick="openStudentForm('${s.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deleteStudent('${s.id}','${esc(s.name)}')">${zh()?'删除':'Delete'}</button></div></div><div class="crud-kv"><div><span>Slug</span><strong>${esc(s.slug)}</strong></div><div><span>${zh()?'年龄':'Age'}</span><strong>${s.age??'—'}</strong></div><div><span>${zh()?'进度':'Progress'}</span><strong>${s.progress??'—'}${s.progress!=null?'%':''}</strong></div></div>${s.parent_notes?`<p class="crud-note">${esc(s.parent_notes)}</p>`:''}</article>`).join('')||`<div class="crud-empty">${zh()?'暂无学生':'No students'}</div>`}</div>`}
  function prep(){return `<div class="crud-toolbar"><div><div class="eyebrow cyan">${zh()?'按学生归档':'BY STUDENT'}</div><h2>${zh()?'备课计划':'Lesson Preparation'}</h2><p class="subtle">${zh()?'下一节或未来几节课按学生分别记录，并可随时手工修改。':'Future sessions are planned independently for each student and can be edited manually at any time.'}</p></div><button class="primary" onclick="openPlanForm()">＋ ${zh()?'新增备课':'New plan'}</button></div><div class="crud-list">${st().students.map(s=>{const rows=st().lesson_plans.filter(p=>p.student_id===s.id&&p.status!=='archived');return `<section class="crud-card"><div class="crud-card-top"><div><div class="eyebrow">${zh()?'学生':'STUDENT'}</div><h3>${esc(s.name)}</h3></div><button class="crud-btn" onclick="openPlanForm('','${s.id}')">＋ ${zh()?'为他备课':'Add plan'}</button></div>${rows.length?rows.map(p=>`<div style="padding:14px 0;border-top:1px solid var(--line);margin-top:10px"><div class="crud-card-top"><div><span class="crud-status">${status('lesson_plans',p.status)}</span><h3>${esc(p.title)}</h3><p>${p.planned_session_number?`${zh()?'预计第':'Session '} ${p.planned_session_number} ${zh()?'节':''}`:''}${p.scheduled_for?` · ${new Date(p.scheduled_for).toLocaleString()}`:''}</p>${p.prep_notes?`<p class="crud-note">${esc(p.prep_notes)}</p>`:''}</div><div class="crud-actions"><button class="crud-btn" onclick="openPlanForm('${p.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deletePlan('${p.id}','${esc(p.title)}')">${zh()?'删除':'Delete'}</button></div></div></div>`).join(''):`<div class="crud-empty">${zh()?'暂时没有备课计划':'No lesson plans yet'}</div>`}</section>`}).join('')}</div>`}
  function content(){const groups=[['idea',zh()?'头脑风暴 / 灵感':'Brainstorm / Ideas'],['draft',zh()?'草稿 / 口播稿':'Drafts / Scripts'],['ready',zh()?'待发布':'Ready to Publish'],['published',zh()?'已发布':'Published']];return `<div class="crud-toolbar"><div><div class="eyebrow cyan">REDNOTE STUDIO</div><h2>${zh()?'小红书内容工作室':'Rednote Content Studio'}</h2><p class="subtle">${zh()?'从想法到发布，全流程可手工增删查改；大部分时候也可以直接让我代你操作。':'Full manual CRUD from idea to publish, while ChatGPT can still handle most updates for you.'}</p></div><button class="primary" onclick="openContentForm()">＋ ${zh()?'新增内容':'New content'}</button></div><div class="crud-sections">${groups.map(([ss,label])=>`<section class="crud-column"><h3>${label} <span class="crud-badge">${st().content_items.filter(c=>c.status===ss).length}</span></h3><div class="crud-list">${st().content_items.filter(c=>c.status===ss).map(c=>`<article class="crud-card"><span class="crud-status">${status('content_items',c.status)}</span><h3>${esc(c.title)}</h3><p>${esc(c.hook||c.body||'').slice(0,220)}</p><div class="crud-actions"><button class="crud-btn" onclick="openContentForm('${c.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deleteContent('${c.id}','${esc(c.title)}')">${zh()?'删除':'Delete'}</button></div></article>`).join('')||`<div class="crud-empty">${zh()?'暂无内容':'Empty'}</div>`}</div></section>`).join('')}</div>`}
  const oldGo=window.go;
  window.go=function(p){if(['students','prep','content'].includes(p)){current=p;const title=document.getElementById('pageTitle');if(title)title.textContent=p==='students'?(zh()?'学生管理':'Student Management'):p==='prep'?(zh()?'备课中心':'Lesson Prep'):(zh()?'小红书内容工作室':'Rednote Studio');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick')===`go('${p}')`));document.getElementById('content').innerHTML=p==='students'?students():p==='prep'?prep():content();return}oldGo(p)};
  const oldLang=window.setLanguage;window.setLanguage=function(n){oldLang(n);if(['students','prep','content'].includes(current))window.go(current)};
  window.renderCrudCurrent=function(){if(['students','prep','content'].includes(current))window.go(current)};
  window.addEventListener('load',()=>setTimeout(()=>{if(['students','prep','content'].includes(current))window.go(current)},400));
})();
