(()=>{
  const zh=()=>((typeof lang!=='undefined'?lang:'zh')==='zh');
  const state=window.STUDIO_CRUD={students:[],lesson_plans:[],content_items:[],loaded:false};
  const api=async(method='GET',body=null,entity='')=>{const url=entity?`/api/crud?entity=${encodeURIComponent(entity)}`:'/api/crud';const r=await fetch(url,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):null});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d};
  async function loadCrud(){try{const [s,p,c]=await Promise.all(['students','lesson_plans','content_items'].map(e=>api('GET',null,e)));state.students=s.items||[];state.lesson_plans=p.items||[];state.content_items=c.items||[];state.loaded=true;if(typeof render==='function')render()}catch(e){console.warn('CRUD load failed',e)}}
  window.reloadCrud=loadCrud;
  const byStudent=id=>state.students.find(s=>s.id===id);
  const statusName=(entity,s)=>{const m={students:{active:['学习中','Active'],paused:['暂停','Paused'],completed:['已完成','Completed']},lesson_plans:{planned:['计划中','Planned'],ready:['已备好','Ready'],completed:['已完成','Completed'],archived:['已归档','Archived']},content_items:{idea:['灵感','Idea'],draft:['草稿','Draft'],ready:['待发布','Ready'],published:['已发布','Published'],archived:['已归档','Archived']}};return m[entity]?.[s]?.[zh()?0:1]||s||''};
  function showModal(html){const m=document.getElementById('modal');m.classList.remove('hidden');m.classList.add('crud-modal');m.innerHTML=`<div class="modal-card glass">${html}</div>`}
  function val(id){return document.getElementById(id)?.value??''}
  async function mutate(action,entity,id,payload){try{await api('POST',{action,entity,id,payload});await loadCrud();if(window.connectStudioMemory)await connectStudioMemory(false);closeModal()}catch(e){alert(e.message)}}
  window.openStudentForm=function(id=''){const s=state.students.find(x=>x.id===id)||{};showModal(`<div class="eyebrow cyan">${zh()?'学生数据库':'STUDENT DATABASE'}</div><h2>${id?(zh()?'编辑学生':'Edit student'):(zh()?'新增学生':'Add student')}</h2><div class="crud-form">
    <label>${zh()?'姓名':'Name'}<input id="cf_name" value="${esc(s.name||'')}"></label><label>Slug<input id="cf_slug" value="${esc(s.slug||'')}"></label>
    <label>${zh()?'年龄':'Age'}<input id="cf_age" type="number" value="${s.age??''}"></label><label>${zh()?'状态':'Status'}<select id="cf_status"><option value="active" ${s.status==='active'?'selected':''}>${statusName('students','active')}</option><option value="paused" ${s.status==='paused'?'selected':''}>${statusName('students','paused')}</option><option value="completed" ${s.status==='completed'?'selected':''}>${statusName('students','completed')}</option></select></label>
    <label class="wide">${zh()?'当前阶段':'Current level'}<input id="cf_level" value="${esc(s.current_level||'')}"></label><label class="wide">${zh()?'当前项目':'Current project'}<input id="cf_project" value="${esc(s.current_project||'')}"></label>
    <label>${zh()?'进度 0-100':'Progress 0-100'}<input id="cf_progress" type="number" min="0" max="100" value="${s.progress??''}"></label><label class="wide">${zh()?'家长/内部备注':'Parent / internal notes'}<textarea id="cf_notes">${esc(s.parent_notes||'')}</textarea></label>
  </div><div class="modal-actions"><button class="ghost" onclick="closeModal()">${zh()?'取消':'Cancel'}</button><button class="primary" onclick="saveStudent('${esc(id)}')">${zh()?'保存':'Save'}</button></div>`)};
  window.saveStudent=function(id=''){mutate(id?'update':'create','students',id,{name:val('cf_name'),slug:val('cf_slug'),age:val('cf_age'),status:val('cf_status'),current_level:val('cf_level'),current_project:val('cf_project'),progress:val('cf_progress'),parent_notes:val('cf_notes')})};
  window.deleteStudent=function(id,name){if(!confirm(zh()?`永久删除学生「${name}」？相关级联数据也可能被删除。此操作不可撤销。`:`Permanently delete ${name}? Related cascading records may also be removed. This cannot be undone.`))return;mutate('delete','students',id,{})};

  window.openPlanForm=function(id='',studentId=''){const p=state.lesson_plans.find(x=>x.id===id)||{};const sid=p.student_id||studentId||state.students[0]?.id||'';showModal(`<div class="eyebrow cyan">${zh()?'备课数据库':'LESSON PREP DATABASE'}</div><h2>${id?(zh()?'编辑备课计划':'Edit lesson plan'):(zh()?'新增备课计划':'New lesson plan')}</h2><div class="crud-form">
    <label>${zh()?'学生':'Student'}<select id="cf_student">${state.students.map(s=>`<option value="${s.id}" ${s.id===sid?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>${zh()?'预计第几节':'Planned session #'}<input id="cf_session" type="number" value="${p.planned_session_number??''}"></label>
    <label class="wide">${zh()?'标题':'Title'}<input id="cf_title" value="${esc(p.title||'')}"></label><label>${zh()?'预计时间':'Scheduled for'}<input id="cf_date" type="datetime-local" value="${p.scheduled_for?new Date(p.scheduled_for).toISOString().slice(0,16):''}"></label><label>${zh()?'状态':'Status'}<select id="cf_pstatus">${['planned','ready','completed','archived'].map(x=>`<option value="${x}" ${p.status===x?'selected':''}>${statusName('lesson_plans',x)}</option>`).join('')}</select></label>
    <label class="wide">${zh()?'学习目标（一行一个）':'Goals (one per line)'}<textarea id="cf_goals">${esc((p.goals||[]).join('\n'))}</textarea></label><label class="wide">${zh()?'课堂流程（一行一个）':'Agenda (one per line)'}<textarea id="cf_agenda">${esc((p.agenda||[]).join('\n'))}</textarea></label>
    <label class="wide">${zh()?'备课备注':'Prep notes'}<textarea id="cf_pnotes">${esc(p.prep_notes||'')}</textarea></label><label class="wide">${zh()?'材料/链接（一行一个）':'Materials / links (one per line)'}<textarea id="cf_materials">${esc((p.materials||[]).join('\n'))}</textarea></label>
  </div><div class="modal-actions"><button class="ghost" onclick="closeModal()">${zh()?'取消':'Cancel'}</button><button class="primary" onclick="savePlan('${esc(id)}')">${zh()?'保存':'Save'}</button></div>`)};
  window.savePlan=function(id=''){mutate(id?'update':'create','lesson_plans',id,{student_id:val('cf_student'),planned_session_number:val('cf_session'),title:val('cf_title'),scheduled_for:val('cf_date')?new Date(val('cf_date')).toISOString():null,status:val('cf_pstatus'),goals:val('cf_goals'),agenda:val('cf_agenda'),prep_notes:val('cf_pnotes'),materials:val('cf_materials')})};
  window.deletePlan=function(id,title){if(confirm(zh()?`删除备课计划「${title}」？`:`Delete lesson plan “${title}”?`))mutate('delete','lesson_plans',id,{})};

  window.openContentForm=function(id=''){const c=state.content_items.find(x=>x.id===id)||{};showModal(`<div class="eyebrow cyan">${zh()?'小红书内容数据库':'REDNOTE CONTENT DATABASE'}</div><h2>${id?(zh()?'编辑内容':'Edit content'):(zh()?'新增内容':'New content')}</h2><div class="crud-form">
    <label class="wide">${zh()?'标题':'Title'}<input id="cf_ctitle" value="${esc(c.title||'')}"></label><label>${zh()?'内容类型/栏目':'Pillar'}<input id="cf_pillar" value="${esc(c.pillar||'')}"></label><label>${zh()?'状态':'Status'}<select id="cf_cstatus">${['idea','draft','ready','published'].map(x=>`<option value="${x}" ${c.status===x?'selected':''}>${statusName('content_items',x)}</option>`).join('')}</select></label>
    <label class="wide">Hook / ${zh()?'开头':'Opening'}<textarea id="cf_hook">${esc(c.hook||'')}</textarea></label><label class="wide">${zh()?'正文 / 口播稿 / 草稿':'Body / script / draft'}<textarea id="cf_body" style="min-height:220px">${esc(c.body||'')}</textarea></label><label class="wide">${zh()?'来源备注':'Source note'}<input id="cf_source" value="${esc(c.source_label||'')}"></label>
  </div><div class="modal-actions"><button class="ghost" onclick="closeModal()">${zh()?'取消':'Cancel'}</button><button class="primary" onclick="saveContent('${esc(id)}')">${zh()?'保存':'Save'}</button></div>`)};
  window.saveContent=function(id=''){mutate(id?'update':'create','content_items',id,{title:val('cf_ctitle'),platform:'Rednote',pillar:val('cf_pillar'),status:val('cf_cstatus'),hook:val('cf_hook'),body:val('cf_body'),source_label:val('cf_source')})};
  window.deleteContent=function(id,title){if(confirm(zh()?`删除内容「${title}」？`:`Delete content “${title}”?`))mutate('delete','content_items',id,{})};

  const oldStudents=studentsPage;studentsPage=function(){const base=oldStudents();return `<div class="crud-toolbar"><div><div class="eyebrow cyan">${zh()?'学生数据库':'STUDENT DATABASE'}</div><h2>${zh()?'学生管理':'Student management'}</h2></div><button class="primary" onclick="openStudentForm()">＋ ${zh()?'新增学生':'Add student'}</button></div>${base}<div class="section-title"><div><h3>${zh()?'数据库操作':'Database controls'}</h3></div></div><div class="crud-list">${state.students.map(s=>`<article class="crud-card"><div class="crud-card-top"><div><span class="crud-status">${statusName('students',s.status)}</span><h3>${esc(s.name)}</h3><p>${esc(s.current_project||'')}</p></div><div class="crud-actions"><button class="crud-btn" onclick="openStudentForm('${s.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deleteStudent('${s.id}','${esc(s.name)}')">${zh()?'删除':'Delete'}</button></div></div><div class="crud-kv"><div><span>Slug</span><strong>${esc(s.slug)}</strong></div><div><span>${zh()?'年龄':'Age'}</span><strong>${s.age??'—'}</strong></div><div><span>${zh()?'进度':'Progress'}</span><strong>${s.progress??'—'}${s.progress!=null?'%':''}</strong></div></div></article>`).join('')}</div>`};

  window.prepPage=function(){const groups=state.students.map(s=>({s,plans:state.lesson_plans.filter(p=>p.student_id===s.id&&p.status!=='archived')}));return `<div class="crud-toolbar"><div><div class="eyebrow cyan">${zh()?'按学生归档':'BY STUDENT'}</div><h2>${zh()?'备课计划':'Lesson preparation'}</h2><p class="subtle">${zh()?'每个学生有自己独立的后续课程计划；即使主题相同，也按学生分别记录。':'Each student keeps an independent future lesson plan, even when themes overlap.'}</p></div><button class="primary" onclick="openPlanForm()">＋ ${zh()?'新增备课':'New plan'}</button></div><div class="crud-list">${groups.map(({s,plans})=>`<section class="crud-card"><div class="crud-card-top"><div class="crud-student-header">${digitalAvatar({name:s.name})}<div><div class="eyebrow">${zh()?'学生':'STUDENT'}</div><h3>${esc(s.name)}</h3></div></div><button class="crud-btn" onclick="openPlanForm('','${s.id}')">＋ ${zh()?'为他备课':'Add plan'}</button></div>${plans.length?plans.map(p=>`<div style="padding:13px 0;border-top:1px solid var(--line);margin-top:10px"><div class="crud-card-top"><div><span class="crud-status">${statusName('lesson_plans',p.status)}</span><h3>${esc(p.title)}</h3><p>${p.planned_session_number?`${zh()?'预计第':'Session '} ${p.planned_session_number} ${zh()?'节':''}`:''}${p.scheduled_for?` · ${new Date(p.scheduled_for).toLocaleString()}`:''}</p><p class="crud-note">${esc(p.prep_notes||'')}</p></div><div class="crud-actions"><button class="crud-btn" onclick="openPlanForm('${p.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deletePlan('${p.id}','${esc(p.title)}')">${zh()?'删除':'Delete'}</button></div></div></div>`).join(''):`<div class="crud-empty">${zh()?'暂时没有备课计划':'No lesson plans yet'}</div>`}</section>`).join('')}</div>`};

  contentPage=function(){const groups=[['idea',zh()?'头脑风暴 / 灵感':'Brainstorm / ideas'],['draft',zh()?'草稿 / 口播稿':'Drafts / scripts'],['ready',zh()?'待发布':'Ready to publish'],['published',zh()?'已发布':'Published']];return `<div class="crud-toolbar"><div><div class="eyebrow cyan">${zh()?'小红书内容数据库':'REDNOTE CONTENT DATABASE'}</div><h2>${zh()?'小红书内容工作室':'Rednote Content Studio'}</h2><p class="subtle">${zh()?'灵感、草稿、口播稿和已发布内容都在这里直接维护。':'Manage ideas, drafts, scripts, ready items and published posts here.'}</p></div><button class="primary" onclick="openContentForm()">＋ ${zh()?'新增内容':'New content'}</button></div><div class="crud-sections">${groups.map(([status,label])=>`<section class="crud-column"><h3>${label} <span class="crud-badge">${state.content_items.filter(c=>c.status===status).length}</span></h3><div class="crud-list">${state.content_items.filter(c=>c.status===status).map(c=>`<article class="crud-card"><span class="crud-status">${statusName('content_items',c.status)}</span><h3>${esc(c.title)}</h3><p>${esc(c.hook||c.body||'').slice(0,180)}</p><div class="crud-actions"><button class="crud-btn" onclick="openContentForm('${c.id}')">${zh()?'编辑':'Edit'}</button><button class="crud-btn danger" onclick="deleteContent('${c.id}','${esc(c.title)}')">${zh()?'删除':'Delete'}</button></div></article>`).join('')||`<div class="crud-empty">${zh()?'暂无内容':'Empty'}</div>`}</div></section>`).join('')}</div>`};

  const oldNav=navGroups;navGroups=function(){const groups=oldNav();const first=groups[0]?.[1]||[];if(!first.some(x=>x[0]==='prep')){const idx=first.findIndex(x=>x[0]==='sessions');first.splice(idx+1,0,['prep','▤',zh()?'备课':'Lesson Prep'])}return groups};
  const oldRefresh=refreshChrome;refreshChrome=function(){oldRefresh();if(current==='prep')document.getElementById('pageTitle').textContent=zh()?'备课计划':'Lesson Preparation'};
  const oldRender=render;render=function(){if(current==='prep'){document.getElementById('content').innerHTML=prepPage();return}oldRender()};
  const oldSet=window.setLanguage;if(oldSet)window.setLanguage=function(next){oldSet(next);renderNav();render()};
  window.addEventListener('load',loadCrud);
})();
