const app=document.getElementById('parentApp');
const slug=(()=>{const parts=location.pathname.split('/').filter(Boolean);if(parts[0]==='parent'&&parts[1])return decodeURIComponent(parts[1]).toLowerCase();return new URLSearchParams(location.search).get('student')||''})();
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

async function api(method='GET',body=null){const opts={method,credentials:'same-origin',headers:{'Content-Type':'application/json'}};if(body)opts.body=JSON.stringify(body);const r=await fetch(`/api/parent-portal?student=${encodeURIComponent(slug)}`,opts);const data=await r.json().catch(()=>({}));return{r,data};}

function lockView(data){const active=data.portal_active;app.innerHTML=`<section class="lock-card glass"><div class="eyebrow">CHONGYU STUDIO · PRIVATE</div><h1>${esc(data.student?.name||'Student')} Learning Journey</h1><p>${active?'请输入家长访问密码查看课程记录、项目成长和作品证据。':'这个家长页面还没有正式开启。请联系 Chongyu 老师。'}</p>${active?`<input id="accessCode" type="password" placeholder="Access code"><button onclick="unlock()">进入成长档案</button>`:''}</section>`;}

function avatar(name){return `<div class="avatar"><span>${esc((name||'?').slice(0,2).toUpperCase())}</span></div>`;}
function sessionRecordsMap(records){return new Map((records||[]).map(r=>[r.session_id,r]));}

function portfolio(data){const s=data.student;const recMap=sessionRecordsMap(data.records);const sessions=data.sessions||[];const skills=data.skills||[];const artifacts=data.artifacts||[];app.innerHTML=`<div class="topline"><div class="brand">Chongyu <span>Studio</span></div><button class="logout" onclick="logout()">退出</button></div>
<section class="hero glass"><div><div class="eyebrow">PRIVATE LEARNING JOURNEY</div><h1>${esc(s.name)}</h1><p>${esc(data.portal?.intro||'Project-based AI learning portfolio with visible evidence of growth.')}</p><div class="meta"><span class="chip">${esc(s.current_level||'AI Builder')}</span><span class="chip">${esc(s.current_project||'')}</span>${s.age?`<span class="chip">Age ${esc(s.age)}</span>`:''}${data.founder_preview?'<span class="chip">Founder Preview</span>':''}</div></div>${avatar(s.name)}</section>
<div class="grid"><div class="metric glass"><b>${sessions.length}</b><span>课程里程碑</span></div><div class="metric glass"><b>${skills.length}</b><span>成长信号</span></div><div class="metric glass"><b>${artifacts.length}</b><span>作品 / 影像证据</span></div></div>
<section class="section"><div class="section-title"><div><div class="eyebrow">JOURNEY</div><h2>课程成长时间线</h2></div><small>每节课都连接真实项目证据</small></div>${sessions.length?`<div class="timeline">${sessions.map(x=>{const r=recMap.get(x.id)||{};return `<article class="session glass"><div class="session-num">S${esc(x.session_number)}</div><div><div class="eyebrow">SESSION ${esc(x.session_number)}</div><h3>${esc(x.title)}</h3><p>${esc(r.achievement||x.summary||'')}</p>${(x.highlights||[]).length?`<div class="highlights">${x.highlights.slice(0,4).map(h=>`<div><span>✓</span>${esc(h)}</div>`).join('')}</div>`:''}${r.teacher_note?`<p style="margin-top:12px"><b>老师观察：</b>${esc(r.teacher_note)}</p>`:''}</div></article>`}).join('')}</div>`:`<div class="notice">课程已经进入 Studio，但还需要老师完成学生与课程分支的精确映射后再正式分享。</div>`}</section>
<section class="section"><div class="section-title"><div><div class="eyebrow">GROWTH SIGNALS</div><h2>能力成长</h2></div><small>基于真实项目证据</small></div>${skills.length?`<div class="skill-grid">${skills.map(k=>`<div class="skill glass"><div class="skill-head"><span>${esc(k.skill_name)}</span><strong>${esc(k.score??'—')}/10</strong></div><div class="bar"><i style="width:${Math.min(100,Number(k.score||0)*10)}%"></i></div>${k.evidence?`<small>${esc(k.evidence)}</small>`:''}</div>`).join('')}</div>`:`<div class="notice">能力雷达会随着真实课程证据逐步更新，不为了“好看”而编造分数。</div>`}</section>
<section class="section"><div class="section-title"><div><div class="eyebrow">EVIDENCE</div><h2>作品与影像</h2></div><small>图片 · 视频 · Demo · 项目链接</small></div>${artifacts.length?`<div class="artifact-grid">${artifacts.map(a=>`<article class="artifact glass"><strong>${esc(a.title||a.artifact_type)}</strong><small>${esc(a.artifact_type||'artifact')}</small>${a.external_url?`<p><a href="${esc(a.external_url)}" target="_blank" rel="noopener" style="color:var(--cyan)">打开作品 ↗</a></p>`:''}</article>`).join('')}</div>`:`<div class="notice">原始照片和视频还没有上传到 Evidence Gallery。课程来源已经保留，后续可以直接补素材，不需要重做课程记录。</div>`}</section>`;}

async function unlock(){const code=document.getElementById('accessCode')?.value||'';const{r,data}=await api('POST',{student:slug,code});if(!r.ok){alert(data.error||'访问密码不正确');return;}load();}
async function logout(){await api('DELETE',{student:slug});location.reload();}
async function load(){if(!slug){app.innerHTML='<section class="loading-card">Missing student link.</section>';return;}const{r,data}=await api();if(r.status===401){lockView(data);return;}if(!r.ok){app.innerHTML=`<section class="loading-card">${esc(data.error||'Unable to load portal.')}</section>`;return;}portfolio(data);}
window.unlock=unlock;window.logout=logout;load();