const app=document.getElementById('parentApp');
const slug=(()=>{const parts=location.pathname.split('/').filter(Boolean);if(parts[0]==='parent'&&parts[1])return decodeURIComponent(parts[1]).toLowerCase();return new URLSearchParams(location.search).get('student')||''})();
let portalLang=localStorage.getItem('parent_lang')||'zh';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const L={zh:{private:'私人学习成长档案',enter:'请输入家长访问密码查看课程记录、项目成长和作品证据。',closed:'这个家长页面还没有正式开启。请联系 Chongyu 老师。',journey:'课程成长时间线',journeySub:'每一节课都对应真实项目与课堂证据',signals:'能力成长',signalsSub:'基于真实项目证据，而不是考试分数',evidence:'作品与影像',evidenceSub:'图片 · 视频 · Demo · 项目链接',summary:'四节课里的成长变化',next:'下一阶段',logout:'退出',course:'课程里程碑',growth:'成长信号',artifacts:'作品 / 影像证据',noEvidence:'原始照片和视频正在整理进作品与影像库。课程来源已经保留，后续可直接补充。',noSignals:'能力成长会根据真实课堂证据逐步更新，不为了“好看”而编造分数。',summaryText:'四节课里，Marcos 已经从“告诉 AI 我想做什么”，逐渐走到了“发现问题、拆解问题、设计系统、部署作品，并让软件真正影响现实世界”。',nextItems:['继续从 Demo 走向更完整的产品','连接 API 与外部服务','完善数据存储与系统架构','继续探索 AI + 传感器 / 硬件','把技术成果表达成可以展示和分享的作品'],access:'进入成长档案',age:'14 岁',builder:'项目式 AI Builder',teacher:'老师观察'},en:{private:'Private Learning Journey',enter:'Enter the parent access code to view course records, project growth and evidence.',closed:'This parent portal is not active yet. Please contact Chongyu.',journey:'Learning Journey',journeySub:'Every session is tied to real project evidence',signals:'Growth Signals',signalsSub:'Based on observed project evidence, not test scores',evidence:'Project Evidence',evidenceSub:'Images · Video · Demo · Project Links',summary:'Growth across four sessions',next:'What’s Next',logout:'Log out',course:'Course milestones',growth:'Growth signals',artifacts:'Projects / evidence',noEvidence:'Original photos and videos are being organized into the Evidence Gallery. The course sources are already preserved.',noSignals:'Growth signals are updated from real classroom evidence rather than invented scores.',summaryText:'Across four sessions, Marcos has moved from “telling AI what I want” toward identifying problems, decomposing them, designing systems, deploying work, and making software affect the physical world.',nextItems:['Move from demos toward more complete products','Connect APIs and external services','Build stronger data and system architecture','Explore AI + sensors / hardware','Turn technical work into polished, shareable projects'],access:'Enter journey',age:'Age 14',builder:'Project-Based AI Builder',teacher:'Teacher observation'}};
const t=k=>L[portalLang][k]||L.zh[k]||k;
const SESSION_ZH={
  1:{title:'从兴趣开始创造：Minecraft + AI Agent',achievement:'从零编程基础出发，Marcos 以自己最喜欢的 Minecraft 为起点，在 AI Agent 协作下完成了网页版 Minecraft 项目。更重要的是，项目跑起来以后，他主动发现了移动按键错配、饥饿条缺失和掉落伤害缺失等问题，并通过和 AI 反复沟通逐步修正。',highlights:['第一节课就完成了可运行的网页版 Minecraft 项目','主动发现并修复移动按键问题','主动指出 Hunger Bar 与 Fall Damage 等缺失机制','开始形成“测试—发现问题—迭代”的 Debug 思维'],teacher:'Marcos 没有等老师告诉他哪里有问题，而是在作品跑起来后自己判断“哪里不对”，再把 AI 当作协作伙伴去解决问题。这是非常好的早期工程思维信号。'},
  2:{title:'第一次把作品真正上线：云服务器部署',achievement:'Marcos 把第一节课的 Minecraft 项目从本地电脑继续推进到真正的公网环境。他自己研究服务器概念，在 Vultr 创建 VPS，通过 SSH 连接服务器，部署项目，并进一步理解端口与防火墙规则，最终拿到了可以直接发给朋友访问的公网链接。',highlights:['理解 VPS、SSH、端口和防火墙的基本作用','第一次完成“开发 → 部署 → 上线”的完整流程','把自己的项目变成别人可以直接打开的产品','从“能在我电脑上跑”走向“能给别人使用”'],teacher:'这一节最重要的并不是“用了云服务器”，而是 Marcos 第一次真正理解了一个产品从开发环境走向公网访问的完整链路。'},
  3:{title:'开始设计一个真正的 AI 系统',achievement:'这一节先从 Training、Inference、Dataset、Input / Output 这些 AI 基础概念出发，再进入真实系统设计。Marcos 参与拆解了人脸识别门禁：摄像头获取人脸 → AI 判断身份 → 系统确认权限 → 决定开门或拒绝。学习重点开始从“让 AI 写代码”转向“一个完整 AI 产品到底由哪些部分组成”。',highlights:['理解 Training 与 Inference 的区别','理解 Dataset、Input、Output 在 AI 系统里的作用','能够把人脸识别门禁拆成多个系统模块','开始从模型视角走向完整产品和系统视角'],teacher:'这一节的关键变化，是 Marcos 开始意识到“模型只是系统的一部分”。真正能用的 AI 产品还需要权限、数据、交互与业务逻辑。'},
  4:{title:'让软件第一次影响现实世界',achievement:'第四节课从软件进入硬件。Marcos 用“最少必要知识”理解电压、电流、电阻、LED 与面包板，并把摄像头、人脸识别、权限判断、Python 逻辑与 LED / 蜂鸣器串成完整链路。识别成功亮绿灯，识别失败亮红灯并触发蜂鸣器。',highlights:['完成摄像头 → AI → Python → 硬件输出的完整链路','第一次让自己写的软件真正影响物理世界','在蜂鸣器异常时主动检查线路、猜原因并反复测试','从纯软件项目进一步进入 AI + Hardware'],teacher:'当 Marcos 看到自己的 AI 系统真正让绿灯亮起、让蜂鸣器产生反应时，软件第一次从屏幕里“走进了现实世界”。这种即时反馈带来了非常强的成就感和学习动力。'}
};
const SKILL_ZH={
  'AI Collaboration':'AI 协作能力','Debugging':'Debug / 排错能力','Deployment & Systems':'部署与系统理解','AI Fundamentals':'AI 基础理解','System Design':'系统设计','Hardware Integration':'软硬件整合','Independent Problem Solving':'独立解决问题'
};
const SKILL_EVIDENCE_ZH={
  'AI Collaboration':'能够把自己的想法和问题清楚地表达给 AI，并通过多轮沟通推动项目完成。',
  'Debugging':'能主动发现功能缺失、行为异常和硬件问题，并通过测试与迭代寻找原因。',
  'Deployment & Systems':'已经接触并实际使用 VPS、SSH、端口、防火墙和公网部署流程。',
  'AI Fundamentals':'理解 Training、Inference、Dataset、Input 与 Output 等核心概念，并能把它们放进真实系统中理解。',
  'System Design':'开始从“一个模型”进一步思考完整产品所需要的输入、判断、权限、数据与输出。',
  'Hardware Integration':'完成从 AI 软件逻辑到 LED / 蜂鸣器等真实硬件输出的端到端连接。',
  'Independent Problem Solving':'面对陌生问题时愿意先观察、尝试、搜索和验证，而不是等待老师直接给答案。'
};
async function api(method='GET',body=null){const opts={method,credentials:'same-origin',headers:{'Content-Type':'application/json'}};if(body)opts.body=JSON.stringify(body);const r=await fetch(`/api/parent-portal?student=${encodeURIComponent(slug)}`,opts);const data=await r.json().catch(()=>({}));return{r,data};}
function setPortalLang(next){portalLang=next;localStorage.setItem('parent_lang',next);load();}
function topbar(){return `<div class="topline"><div class="brand">Chongyu <span>Studio</span></div><div class="top-actions"><button class="lang-btn ${portalLang==='zh'?'active':''}" onclick="setPortalLang('zh')">中文</button><button class="lang-btn ${portalLang==='en'?'active':''}" onclick="setPortalLang('en')">EN</button><button class="logout" onclick="logout()">${t('logout')}</button></div></div>`;}
function lockView(data){const active=data.portal_active;app.innerHTML=`${topbar()}<section class="lock-card glass"><div class="eyebrow">CHONGYU STUDIO · PRIVATE</div><h1>${esc(data.student?.name||'Student')} ${portalLang==='zh'?'成长档案':'Learning Journey'}</h1><p>${active?t('enter'):t('closed')}</p>${active?`<input id="accessCode" type="password" placeholder="${portalLang==='zh'?'访问密码':'Access code'}"><button onclick="unlock()">${t('access')}</button>`:''}</section>`;}
function signalLabel(score){const n=Number(score||0);if(n>=9)return portalLang==='zh'?'表现突出':'Exceptional';if(n>=8)return portalLang==='zh'?'表现强':'Strong';if(n>=7)return portalLang==='zh'?'持续成长':'Growing';if(n>=5)return portalLang==='zh'?'发展中':'Developing';return portalLang==='zh'?'开始形成':'Emerging';}
function sessionTitle(n,title){return portalLang==='zh'?(SESSION_ZH[n]?.title||title):title;}
function sessionRecordsMap(records){return new Map((records||[]).map(r=>[r.session_id,r]));}
function artifactSession(a){return Number(a?.metadata?.session_number||0)||0;}
function heroPortrait(artifacts,name){const p=(artifacts||[]).find(a=>a.artifact_type==='portrait'&&a.signed_url);return p?`<div class="avatar-photo"><img src="${esc(p.signed_url)}" alt="${esc(name)}"></div>`:`<div class="avatar"><span>${esc((name||'?').slice(0,2).toUpperCase())}</span></div>`;}
function mediaForSession(artifacts,n){return (artifacts||[]).filter(a=>artifactSession(a)===Number(n)&&a.signed_url&&a.artifact_type!=='portrait').slice(0,2);}
function displayProject(raw){if(portalLang==='en')return raw||'AI System · Computer Vision · Hardware';return 'AI 系统 · 计算机视觉 · 硬件';}
function sessionAchievement(x,r){if(portalLang==='zh')return SESSION_ZH[x.session_number]?.achievement||r.achievement||x.summary||'';return r.achievement||x.summary||'';}
function sessionHighlights(x,r){if(portalLang==='zh')return SESSION_ZH[x.session_number]?.highlights||[];return (r.evidence&&Array.isArray(r.evidence)&&r.evidence.length?r.evidence:(x.highlights||[])).slice(0,4);}
function teacherNote(x,r){if(portalLang==='zh')return SESSION_ZH[x.session_number]?.teacher||'';return r.teacher_note||'';}
function skillName(name){return portalLang==='zh'?(SKILL_ZH[name]||name):name;}
function skillEvidence(k){if(portalLang==='zh')return SKILL_EVIDENCE_ZH[k.skill_name]||'';return typeof k.evidence==='string'?k.evidence:JSON.stringify(k.evidence||'');}
function artifactTitle(a){if(portalLang==='en')return a.title||a.artifact_type;const n=artifactSession(a);if(a.artifact_type==='portrait')return 'Marcos 个人头像';if(n===1)return '第一节课 · Minecraft 项目课堂素材';if(n===2)return '第二节课 · 云部署课堂素材';if(n===3)return '第三节课 · Training / Inference 与 AI 系统设计';if(n===4)return '第四节课 · AI + 硬件门禁项目';return a.title||'课程素材';}
function portfolio(data){
  const s=data.student;const recMap=sessionRecordsMap(data.records);const sessions=data.sessions||[];const skills=data.skills||[];const artifacts=data.artifacts||[];
  app.innerHTML=`${topbar()}
<section class="hero glass"><div><div class="eyebrow">${t('private')}</div><h1>${esc(s.name)}</h1><p>${portalLang==='zh'?'用 AI 和编程，把想法变成真正能运行的作品。':'Using AI and coding to turn ideas into real working products.'}</p><div class="meta"><span class="chip">${t('age')}</span><span class="chip">${t('builder')}</span><span class="chip">${esc(displayProject(s.current_project))}</span>${data.founder_preview?'<span class="chip">Founder Preview</span>':''}</div></div>${heroPortrait(artifacts,s.name)}</section>
<div class="grid"><div class="metric glass"><b>${sessions.length}</b><span>${t('course')}</span></div><div class="metric glass"><b>${skills.length}</b><span>${t('growth')}</span></div><div class="metric glass"><b>${artifacts.filter(a=>a.signed_url).length}</b><span>${t('artifacts')}</span></div></div>
<div class="journey-summary"><strong>${t('summary')}</strong><p>${t('summaryText')}</p></div>
<section class="section"><div class="section-title"><div><div class="eyebrow">JOURNEY</div><h2>${t('journey')}</h2></div><small>${t('journeySub')}</small></div>${sessions.length?`<div class="timeline">${sessions.map(x=>{const r=recMap.get(x.id)||{};const hs=sessionHighlights(x,r);const media=mediaForSession(artifacts,x.session_number);const note=teacherNote(x,r);return `<article class="session glass"><div class="session-num">S${esc(x.session_number)}</div><div>${media.length?`<div class="session-media">${media.map(m=>`<img src="${esc(m.signed_url)}" alt="${esc(artifactTitle(m))}">`).join('')}</div>`:''}<div class="eyebrow">${portalLang==='zh'?`第 ${esc(x.session_number)} 节`:`SESSION ${esc(x.session_number)}`}</div><h3>${esc(sessionTitle(x.session_number,x.title))}</h3><p>${esc(sessionAchievement(x,r))}</p>${hs.length?`<div class="highlights">${hs.map(h=>`<div><span>✓</span>${esc(typeof h==='string'?h:(h.label||h.text||''))}</div>`).join('')}</div>`:''}${note?`<p style="margin-top:12px"><b>${t('teacher')}：</b>${esc(note)}</p>`:''}</div></article>`}).join('')}</div>`:`<div class="notice">${portalLang==='zh'?'课程记录正在整理。':'Course records are being prepared.'}</div>`}</section>
<section class="section"><div class="section-title"><div><div class="eyebrow">GROWTH SIGNALS</div><h2>${t('signals')}</h2></div><small>${t('signalsSub')}</small></div>${skills.length?`<div class="skill-grid">${skills.map(k=>`<div class="skill glass"><div class="skill-head"><span>${esc(skillName(k.skill_name))}</span><strong>${signalLabel(k.score)}</strong></div><div class="bar"><i style="width:${Math.min(100,Number(k.score||0)*10)}%"></i></div>${skillEvidence(k)?`<small>${esc(skillEvidence(k))}</small>`:''}</div>`).join('')}</div>`:`<div class="notice">${t('noSignals')}</div>`}</section>
<section class="section"><div class="section-title"><div><div class="eyebrow">EVIDENCE</div><h2>${t('evidence')}</h2></div><small>${t('evidenceSub')}</small></div>${artifacts.some(a=>a.signed_url)?`<div class="artifact-gallery">${artifacts.filter(a=>a.signed_url).map(a=>`<article class="artifact-tile glass"><img src="${esc(a.signed_url)}" alt="${esc(artifactTitle(a))}"><div><strong>${esc(artifactTitle(a))}</strong><small>${artifactSession(a)?`${portalLang==='zh'?`第 ${artifactSession(a)} 节`:`Session ${artifactSession(a)}`}`:a.artifact_type}</small></div></article>`).join('')}</div>`:`<div class="notice">${t('noEvidence')}</div>`}</section>
<section class="section"><div class="section-title"><div><div class="eyebrow">NEXT</div><h2>${t('next')}</h2></div></div><div class="next-card glass"><ul>${t('nextItems').map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section>`;
}
async function unlock(){const code=document.getElementById('accessCode')?.value||'';const{r,data}=await api('POST',{student:slug,code});if(!r.ok){alert(data.error||'访问密码不正确');return;}load();}
async function logout(){await api('DELETE',{student:slug});location.reload();}
async function load(){if(!slug){app.innerHTML='<section class="loading-card">Missing student link.</section>';return;}const{r,data}=await api();if(r.status===401){lockView(data);return;}if(!r.ok){app.innerHTML=`<section class="loading-card">${esc(data.error||'Unable to load portal.')}</section>`;return;}portfolio(data);}
window.unlock=unlock;window.logout=logout;window.setPortalLang=setPortalLang;load();