(() => {
  const state = window.STUDIO_LIVE_STATE = { mode:'locked', loadedAt:null, error:null };
  const langNow=()=>typeof lang!=='undefined'?lang:'zh';
  const bi=(en,zh)=>({en,zh});
  const tr=(row,field,fallback='')=>{const z=row?.translations?.zh?.[field],e=row?.translations?.en?.[field];return bi(e??fallback??'',z??fallback??'')};
  const skillZh={'AI Collaboration':'AI 协作能力','Debugging':'调试能力','Deployment & Systems':'部署与系统能力','AI Fundamentals':'AI 基础理解','System Design':'系统设计','Hardware Integration':'软硬件整合','Independent Problem Solving':'独立解决问题'};
  async function sessionStatus(){try{const r=await fetch('/api/session',{credentials:'same-origin'});const d=await r.json().catch(()=>({}));return Boolean(r.ok&&d.authenticated)}catch{return false}}
  async function unlock(){const token=prompt(langNow()==='zh'?'请输入 Studio Access Token':'Enter Studio Access Token')||'';if(!token)return false;const r=await fetch('/api/session',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});if(!r.ok){alert(langNow()==='zh'?'Access Token 不正确':'Invalid access token');return false}return true}
  function setStatus(mode,detail=''){const el=document.getElementById('memoryStatus');if(!el)return;el.textContent=mode==='live'?(langNow()==='zh'?'● Supabase 公司记忆在线':'● Supabase company memory online'):mode==='error'?(langNow()==='zh'?`记忆连接失败${detail?' · '+detail:''}`:`Memory connection failed${detail?' · '+detail:''}`):(langNow()==='zh'?'🔒 点击连接公司记忆':'🔒 Click to connect company memory');el.onclick=()=>connectStudioMemory(true);el.style.cursor='pointer'}
  function configure(){const zh=langNow()==='zh';const b=document.getElementById('modelBtn');if(b){b.textContent=zh?'ChatGPT · 主 AI 操作员':'ChatGPT · Primary AI Operator';b.disabled=true}const u=document.getElementById('uploadBtn');if(u)u.textContent=zh?'↑ AI 素材箱':'↑ AI Media Inbox';const brand=document.getElementById('brandSub');if(brand)brand.textContent=zh?'AI 教育操作系统':'AI Education OS'}
  function latestMetric(metrics,id){return metrics.find(x=>x.content_id===id)||null}
  function zhSource(s){return String(s||'').replace(/Lesson\s*(\d+)/i,'第 $1 节').replace(/Rednote/gi,'小红书')}
  function hydrate(raw){
    const rows=raw.data||{};const lessonsBy=new Map();(rows.lessons||[]).forEach(x=>{if(!lessonsBy.has(x.student_id))lessonsBy.set(x.student_id,[]);lessonsBy.get(x.student_id).push(x)});
    const sessions=new Map((rows.course_sessions||[]).map(x=>[x.id,x]));const recBy=new Map();(rows.student_session_records||[]).forEach(r=>{if(!recBy.has(r.student_id))recBy.set(r.student_id,[]);if(sessions.has(r.session_id))recBy.get(r.student_id).push({...r,session:sessions.get(r.session_id)})});
    const skillsBy=new Map();(rows.student_skills||[]).forEach(s=>{if(!skillsBy.has(s.student_id))skillsBy.set(s.student_id,[]);skillsBy.get(s.student_id).push({name:bi(s.translations?.en?.skill_name||s.skill_name,s.translations?.zh?.skill_name||skillZh[s.skill_name]||s.skill_name),score:Number(s.score||0),evidence:bi(s.translations?.en?.evidence||String(s.evidence||''),s.translations?.zh?.evidence||String(s.evidence||''))})});
    D.students=(rows.students||[]).map(s=>({id:s.slug,dbId:s.id,name:s.name,age:s.age,level:tr(s,'current_level',s.current_level),project:tr(s,'current_project',s.current_project),status:bi(s.status||'active',s.status==='active'?'学习中':s.status||''),progress:s.progress,skills:skillsBy.get(s.id)||[],lessons:(lessonsBy.get(s.id)||[]).map(l=>({id:l.id,n:l.lesson_number||0,title:bi(l.title||'',l.title||''),achievement:bi(l.achievement||l.summary||'',l.achievement||l.summary||''),difficulty:bi(l.difficulty||'',l.difficulty||''),nextStep:bi(l.next_step||'',l.next_step||'')})),sessions:(recBy.get(s.id)||[]).sort((a,b)=>a.session.session_number-b.session.session_number).map(r=>({id:r.session.id,n:r.session.session_number,title:tr(r.session,'title',r.session.title),track:tr(r,'track',r.track),achievement:tr(r,'achievement',r.achievement),difficulty:tr(r,'difficulty',r.difficulty),nextStep:tr(r,'next_step',r.next_step),teacherNote:tr(r,'teacher_note',r.teacher_note),evidence:r.evidence||[],session:r.session}))}));
    D.sessions=(rows.course_sessions||[]).map(s=>({id:s.id,n:s.session_number,title:tr(s,'title',s.title),summary:tr(s,'summary',s.summary),goals:s.learning_goals||[],concepts:bi(s.translations?.en?.concepts||s.concepts||[],s.translations?.zh?.concepts||s.concepts||[]),highlights:bi(s.translations?.en?.highlights||s.highlights||[],s.translations?.zh?.highlights||s.highlights||[]),reflection:tr(s,'teacher_reflection',s.teacher_reflection),sourceUrl:s.source_url||'',sourcePlatform:s.source_platform||'',media:s.media||[],status:s.status||'published'}));
    D.artifacts=rows.artifacts||[];D.parentPortals=(rows.parent_portals||[]).map(p=>({...p,student:D.students.find(s=>s.dbId===p.student_id)||null}));
    D.content=(rows.content_items||[]).map(c=>{const m=latestMetric(rows.content_metrics||[],c.id),src=c.source_label||c.source_type||'';return{id:c.id,title:tr(c,'title',c.title),pillar:tr(c,'pillar',c.pillar),hook:tr(c,'hook',c.hook),body:tr(c,'body',c.body),status:c.status?c.status[0].toUpperCase()+c.status.slice(1):'Idea',views:m?.views??null,saves:m?.saves??null,leads:m?.leads??null,source:bi(src,zhSource(src))}});
    D.brain=(rows.company_brain||[]).map(b=>({id:b.id,type:bi(b.brain_type||'Insight',b.brain_type==='principle'?'原则':'洞察'),title:bi(b.title||'',b.title||''),body:bi(b.body||'',b.body||''),evidence:[]}));
    D.inbox=(rows.inbox_items||[]).map(i=>({id:i.id,type:bi(i.input_type||'Note',i.input_type==='founder_note'?'创始人记录':'记录'),title:bi(i.raw_content||'',i.raw_content||''),meta:bi(new Date(i.created_at).toLocaleString(),new Date(i.created_at).toLocaleString()),status:i.status==='processed'?'Processed':'Proposed'}));
    D.decisions=rows.decisions||[];D.memoryItems=rows.memory_items||[];D.liveStats={students:D.students.length,sessions:D.sessions.length,content:D.content.filter(x=>x.status==='Published').length,drafts:D.content.filter(x=>x.status==='Draft').length,brain:D.brain.length,inboxNew:(rows.inbox_items||[]).filter(x=>x.status==='new').length,evidence:D.artifacts.length};
    state.mode='live';state.loadedAt=new Date().toISOString();state.error=null;setStatus('live');configure();if(D.students.length&&!D.students.some(s=>s.id===selectedStudent))selectedStudent=D.students[0].id;render();
  }
  async function fetchData(){const r=await fetch('/api/studio-bootstrap',{credentials:'same-origin'});const data=await r.json().catch(()=>({}));return{r,data}}
  window.connectStudioMemory=async function(promptIfMissing=true){try{let{r,data}=await fetchData();if(r.status===401&&promptIfMissing){if(!(await unlock())){setStatus('locked');return false}({r,data}=await fetchData())}if(r.status===401){setStatus('locked');return false}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);hydrate(data);return true}catch(e){state.mode='error';state.error=e.message;setStatus('error',e.message.slice(0,60));return false}};
  window.openInboxComposer=function(){const m=document.getElementById('modal');m.classList.remove('hidden');m.innerHTML=`<div class="modal-card glass"><div class="eyebrow">${langNow()==='zh'?'统一收件箱':'UNIVERSAL INBOX'}</div><h2>${langNow()==='zh'?'记录到公司记忆':'Capture to company memory'}</h2><textarea id="liveCaptureText" placeholder="${langNow()==='zh'?'课堂观察、想法、决策、待办……':'Class observation, idea, decision, task…'}"></textarea><div class="modal-actions"><button class="ghost" onclick="closeModal()">${langNow()==='zh'?'取消':'Cancel'}</button><button class="primary" onclick="submitLiveCapture()">${langNow()==='zh'?'保存':'Save'}</button></div></div>`};
  window.submitLiveCapture=async function(){const content=document.getElementById('liveCaptureText')?.value.trim();if(!content)return;if(!(await sessionStatus())&&!(await unlock()))return;const r=await fetch('/api/studio-data',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'capture',payload:{input_type:'founder_note',content}})});if(!r.ok){const d=await r.json().catch(()=>({}));alert(d.error||'Save failed');return}closeModal();await connectStudioMemory(false)};
  window.studioAction=async function(action,payload={}){if(!(await sessionStatus())&&!(await unlock()))throw new Error('Founder session required.');const r=await fetch('/api/studio-data',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);await connectStudioMemory(false);return d};
  const base=window.setLanguage;if(base)window.setLanguage=function(next){base(next);setStatus(state.mode,state.error||'');configure()};window.addEventListener('load',async()=>{setStatus('locked');configure();await connectStudioMemory(false)});
})();