(()=>{
  const EXT=window.STUDIO_EXT={lessonPlans:[],calendarEvents:[],actionItems:[],dailyBriefs:[],loaded:false};
  const zh=()=>lang==='zh';
  const fmtDate=v=>{if(!v)return '—';const d=new Date(v);return d.toLocaleDateString(zh()?'zh-CN':'en-CA',{month:'short',day:'numeric'});};
  const fmtTime=v=>{if(!v)return '';const d=new Date(v);return d.toLocaleTimeString(zh()?'zh-CN':'en-CA',{hour:'2-digit',minute:'2-digit'});};
  const esc2=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const studentById=id=>(D.students||[]).find(s=>s.dbId===id);
  const lz=n=>String(n).padStart(2,'0');
  let calCursor=new Date();calCursor.setDate(1);

  const NAV=()=>[
    ['WORKSPACE',[
      ['command','◈',zh()?'指挥中心':'Command Center'],['students','◉',zh()?'学生':'Students'],['courses','⌁',zh()?'过往课程':'Course History'],['prep','✎',zh()?'备课':'Lesson Prep'],['content','✦',zh()?'小红书工作室':'Rednote Studio'],['calendar','▦',zh()?'课程日历':'Course Calendar']
    ]],
    ['SYSTEM',[
      ['inbox','◎',zh()?'收件箱':'Inbox'],['brain','◇',zh()?'公司大脑':'Company Brain'],['workflows','⚡',zh()?'AI 工作流':'AI Workflows'],['parent','↗',zh()?'家长分享':'Parent Share']
    ]]
  ];

  function v2Nav(){const nav=document.getElementById('nav');if(!nav)return;nav.innerHTML=NAV().map(([g,items])=>`<div class="nav-section">${g}</div>${items.map(([p,i,l])=>`<button class="nav-item ${current===p?'active':''}" onclick="go('${p}')"><span class="nav-icon">${i}</span><span>${l}</span></button>`).join('')}`).join('');}
  function pageTitle(){const map={command:['指挥中心','Command Center'],students:['学生成长档案','Student Intelligence'],courses:['过往课程','Course History'],prep:['备课中心','Lesson Prep'],content:['小红书内容工作室','Rednote Content Studio'],calendar:['课程日历','Course Calendar'],inbox:['统一收件箱','Universal Inbox'],brain:['公司大脑','Company Brain'],workflows:['AI 工作流','AI Workflows'],parent:['家长分享','Parent Share']};return (map[current]||map.command)[zh()?0:1];}
  function chrome(){const p=document.getElementById('pageTitle');if(p)p.textContent=pageTitle();const w=document.getElementById('workspaceLabel');if(w)w.textContent=zh()?'创始人控制台':'Founder Control Deck';const sub=document.getElementById('brandSub');if(sub)sub.textContent=zh()?'AI 教育操作系统':'AI Education OS';const upload=document.getElementById('uploadBtn');if(upload)upload.textContent=zh()?'↑ AI 素材箱':'↑ AI Media Inbox';const cap=document.getElementById('captureBtn');if(cap)cap.textContent=zh()?'+ 记录':'+ Capture';document.getElementById('langZh')?.classList.toggle('active',zh());document.getElementById('langEn')?.classList.toggle('active',!zh());}
  window.go=function(p){current=p;chrome();v2Nav();v2Render();};
  window.setLanguage=function(n){lang=n;localStorage.setItem('studio_lang',n);document.documentElement.lang=n==='zh'?'zh-CN':'en';chrome();v2Nav();v2Render();};

  async function ops(action,payload={}){const r=await fetch('/api/ops',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
  async function loadExt(){try{const r=await fetch('/api/ops',{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();Object.assign(EXT,{lessonPlans:d.data?.lesson_plans||[],calendarEvents:d.data?.calendar_events||[],actionItems:d.data?.action_items||[],dailyBriefs:d.data?.daily_briefs||[],loaded:true});const local=new Date();const day=`${local.getFullYear()}-${lz(local.getMonth()+1)}-${lz(local.getDate())}`;await ops('refresh_daily_brief',{local_date:day}).catch(()=>null);const r2=await fetch('/api/ops',{credentials:'same-origin'});if(r2.ok){const d2=await r2.json();Object.assign(EXT,{lessonPlans:d2.data?.lesson_plans||[],calendarEvents:d2.data?.calendar_events||[],actionItems:d2.data?.action_items||[],dailyBriefs:d2.data?.daily_briefs||[],loaded:true});}v2Render();}catch(e){console.warn('ops bootstrap',e);}}

  function moduleCard(icon,title,desc,meta,page){return `<button class="module-card glass" onclick="go('${page}')"><div class="module-icon">${icon}</div><div><h3>${title}</h3><p>${desc}</p><span>${meta} →</span></div></button>`;}
  function currentBrief(){return EXT.dailyBriefs?.[0]||null;}
  function briefPanel(){const b=currentBrief();const open=(EXT.actionItems||[]).filter(x=>x.status==='open');const urgent=open.filter(x=>x.priority==='urgent'||x.priority==='high');const todayEvents=(EXT.calendarEvents||[]).filter(e=>new Date(e.start_at).toDateString()===new Date().toDateString());const next=(EXT.calendarEvents||[]).filter(e=>new Date(e.start_at)>new Date()).slice(0,4);return `<section class="daily-brief glass"><div class="brief-head"><div><div class="eyebrow cyan">${zh()?'每日运营简报':'DAILY OPERATING BRIEF'}</div><h2>${zh()?'今天先做什么？':'What matters today?'}</h2></div><span class="brief-date">${new Date().toLocaleDateString(zh()?'zh-CN':'en-CA',{weekday:'long',month:'long',day:'numeric'})}</span></div><div class="brief-grid"><div class="brief-main"><h4>${zh()?'今日总结':'Summary'}</h4><p>${zh()?(b?.summary||`当前有 ${D.students?.length||0} 名活跃学生。`):`${D.students?.length||0} active students · ${next.length} upcoming events.`}</p><h4>${zh()?'复盘 / 判断':'Review'}</h4><p>${zh()?(b?.review||'保持课程、备课、内容与学生证据同步更新。'):'Keep course records, prep, content and evidence synchronized.'}</p></div><div class="brief-list"><h4>${zh()?'紧急 / 高优先级':'Urgent'}</h4>${urgent.length?urgent.slice(0,4).map(x=>`<div class="brief-item urgent"><b>${esc2(x.title)}</b><small>${x.due_at?fmtDate(x.due_at):zh()?'尽快处理':'ASAP'}</small></div>`).join(''):`<div class="brief-empty">${zh()?'暂无高优先级阻塞':'No urgent blockers'}</div>`}<h4>${zh()?'今天与接下来':'Today & next'}</h4>${[...todayEvents,...next].slice(0,4).map(x=>`<div class="brief-item"><b>${esc2(x.title)}</b><small>${fmtDate(x.start_at)} ${fmtTime(x.start_at)}</small></div>`).join('')||`<div class="brief-empty">${zh()?'日历还没有安排':'Nothing scheduled yet'}</div>`}</div><div class="brief-list"><h4>${zh()?'AI 推荐 Idea':'AI ideas'}</h4>${(b?.ideas||[]).slice(0,4).map(x=>`<div class="idea-item"><b>${esc2(x.title)}</b><p>${esc2(x.reason)}</p></div>`).join('')||`<div class="idea-item"><b>${zh()?'从最近课堂提炼故事':'Mine the latest class story'}</b><p>${zh()?'优先找“遇到问题→自主解决→能力变化”的片段。':'Look for problem → self-driven solution → visible growth.'}</p></div>`}</div></div></section>`;}

  function command(){const plans=(EXT.lessonPlans||[]).filter(x=>x.status!=='completed').length,upcoming=(EXT.calendarEvents||[]).filter(e=>new Date(e.start_at)>new Date()).length,ideas=(D.content||[]).filter(c=>['Idea','Draft','Ready'].includes(c.status)).length;return `${briefPanel()}<div class="section-title"><div><div class="eyebrow">${zh()?'工作模块':'WORKSPACE MODULES'}</div><h3>${zh()?'所有工作从这里进入':'Everything in one operating view'}</h3></div></div><div class="module-grid">${moduleCard('◉',zh()?'学生档案':'Students',zh()?'每个学生独立成长记录、证据与家长页':'Individual growth records, evidence and parent views',`${D.students?.length||0} ${zh()?'名学生':'students'}`,'students')}${moduleCard('⌁',zh()?'过往课程':'Course History',zh()?'按学生归档，每个人的课堂记录独立保存':'Per-student history; same curriculum can still have different records',`${(D.students||[]).reduce((n,s)=>n+(s.sessions?.length||0)+(s.lessons?.length||0),0)} ${zh()?'条个人记录':'student records'}`,'courses')}${moduleCard('✎',zh()?'备课中心':'Lesson Prep',zh()?'按学生管理下一节或未来几节课要上的内容':'Plan each student’s next one or several sessions',`${plans} ${zh()?'个待执行备课':'open plans'}`,'prep')}${moduleCard('✦',zh()?'小红书内容工作室':'Rednote Studio',zh()?'头脑风暴、草稿、口播稿、待发布与已发布内容':'Ideas, drafts, scripts, ready and published content',`${ideas} ${zh()?'个未发布内容':'unpublished items'}`,'content')}${moduleCard('▦',zh()?'课程日历':'Course Calendar',zh()?'像日历一样管理真实课程、备课和内容安排':'Schedule lessons, prep and content in a real calendar',`${upcoming} ${zh()?'个未来安排':'upcoming'}`,'calendar')}</div>`;}

  function courses(){return `<div class="page-intro"><div><div class="eyebrow cyan">${zh()?'逐学生课程档案':'PER-STUDENT COURSE HISTORY'}</div><h2>${zh()?'每个学生都有自己的一份课堂历史':'Every student keeps an individual class history'}</h2><p>${zh()?'即使上的是相同主题，也分别保存该学生当堂做了什么、卡在哪里、成长了什么以及下一步。':'Even when the curriculum overlaps, each student keeps distinct outcomes, challenges, observations and next steps.'}</p></div></div><div class="student-course-groups">${(D.students||[]).map(s=>{const rows=[...(s.sessions||[]),...(s.lessons||[])].sort((a,b)=>(b.n||0)-(a.n||0));return `<section class="student-course-group glass"><div class="student-group-head"><div><div class="eyebrow">${zh()?'学生':'STUDENT'}</div><h3>${esc2(s.name)}</h3></div><span>${rows.length} ${zh()?'条个人课程记录':'records'}</span></div>${rows.length?`<div class="course-list">${rows.map(r=>`<article><span class="course-no">${r.n?`${zh()?'第':'S'}${r.n}${zh()?'节':''}`:'•'}</span><div><h4>${esc2(tx(r.title))}</h4><p>${esc2(tx(r.achievement||r.track||r.teacherNote||''))}</p>${tx(r.difficulty||'')?`<small>${zh()?'课堂难点':'Challenge'} · ${esc2(tx(r.difficulty))}</small>`:''}</div></article>`).join('')}</div>`:`<div class="empty-state">${zh()?'还没有个人课堂记录':'No student-specific class records yet'}</div>`}</section>`}).join('')}</div>`;}

  function prep(){return `<div class="page-intro row between"><div><div class="eyebrow cyan">${zh()?'下一步教学':'NEXT LESSONS'}</div><h2>${zh()?'按学生管理备课':'Lesson prep by student'}</h2><p>${zh()?'这里记录下一节、下两节甚至未来几节需要上的内容；不和已经发生的课堂混在一起。':'Keep future lesson planning separate from completed class records.'}</p></div><button class="primary" onclick="openPrepModal()">${zh()?'+ 新建备课':'+ New prep'}</button></div><div class="prep-groups">${(D.students||[]).map(s=>{const rows=(EXT.lessonPlans||[]).filter(x=>x.student_id===s.dbId&&x.status!=='archived');return `<section class="prep-group glass"><div class="student-group-head"><div><div class="eyebrow">${zh()?'学生备课':'STUDENT PREP'}</div><h3>${esc2(s.name)}</h3></div><span>${rows.length} ${zh()?'份计划':'plans'}</span></div>${rows.length?rows.map(p=>`<article class="prep-card"><div><span class="chip">${p.planned_session_number?`${zh()?'第':'S'}${p.planned_session_number}${zh()?'节':''}`:zh()?'未来课程':'Future'}</span><h4>${esc2(p.title)}</h4><p>${esc2(p.prep_notes||'')}</p></div><div class="prep-meta"><b>${p.status==='ready'?(zh()?'已准备':'Ready'):(zh()?'计划中':'Planned')}</b><small>${p.scheduled_for?`${fmtDate(p.scheduled_for)} ${fmtTime(p.scheduled_for)}`:(zh()?'未排期':'Unscheduled')}</small></div></article>`).join(''):`<div class="empty-state">${zh()?'还没有备课计划':'No lesson plans yet'}</div>`}</section>`}).join('')}</div>`;}

  function contentStudio(){const groups=[['idea',zh()?'头脑风暴 / 灵感池':'Brainstorm / Ideas'],['draft',zh()?'草稿 / 口播稿':'Drafts / Scripts'],['ready',zh()?'待发布':'Ready to Publish'],['published',zh()?'已发布':'Published']];return `<div class="page-intro"><div><div class="eyebrow cyan">REDNOTE STUDIO</div><h2>${zh()?'小红书内容工作室':'Rednote Content Studio'}</h2><p>${zh()?'把“想到什么”到“正式发布”放在同一条内容流水线上。':'Keep brainstorm, drafts, scripts and published work in one pipeline.'}</p></div></div><div class="content-columns">${groups.map(([st,label])=>{const rows=(D.content||[]).filter(c=>String(c.status||'').toLowerCase()===st);return `<section class="content-column"><div class="content-col-head"><h3>${label}</h3><span>${rows.length}</span></div>${rows.map(c=>`<article class="content-card glass"><div class="eyebrow">${esc2(tx(c.pillar)||'REDNOTE')}</div><h4>${esc2(tx(c.title))}</h4><p>${esc2(tx(c.hook||c.body||'')).slice(0,220)}</p><small>${esc2(tx(c.source)||'')}</small></article>`).join('')||`<div class="empty-state compact">${zh()?'暂无内容':'Empty'}</div>`}</section>`}).join('')}</div>`;}

  function monthGrid(){const y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();const cells=[];for(let i=0;i<42;i++){let d,cm=m,cy=y,muted=false;if(i<start){d=prev-start+i+1;cm=m-1;muted=true;}else if(i>=start+days){d=i-start-days+1;cm=m+1;muted=true;}else d=i-start+1;const date=new Date(cy,cm,d);const ds=`${date.getFullYear()}-${lz(date.getMonth()+1)}-${lz(date.getDate())}`;const events=(EXT.calendarEvents||[]).filter(e=>{const q=new Date(e.start_at);return q.getFullYear()===date.getFullYear()&&q.getMonth()===date.getMonth()&&q.getDate()===date.getDate();});cells.push(`<button class="cal-day ${muted?'muted':''} ${date.toDateString()===new Date().toDateString()?'today':''}" onclick="openCalendarModal('${ds}')"><span>${d}</span>${events.slice(0,3).map(e=>`<i class="cal-event ${e.event_type}">${fmtTime(e.start_at)} ${esc2(e.title)}</i>`).join('')}${events.length>3?`<small>+${events.length-3}</small>`:''}</button>`);}return `<div class="calendar-head"><button onclick="shiftMonth(-1)">‹</button><h3>${calCursor.toLocaleDateString(zh()?'zh-CN':'en-CA',{year:'numeric',month:'long'})}</h3><button onclick="shiftMonth(1)">›</button></div><div class="week-head">${(zh()?['一','二','三','四','五','六','日']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div>`;}
  window.shiftMonth=function(n){calCursor=new Date(calCursor.getFullYear(),calCursor.getMonth()+n,1);v2Render();};
  function calendar(){const next=(EXT.calendarEvents||[]).filter(e=>new Date(e.start_at)>new Date()).slice(0,8);return `<div class="page-intro row between"><div><div class="eyebrow cyan">${zh()?'真实课程安排':'LIVE SCHEDULE'}</div><h2>${zh()?'课程日历':'Course Calendar'}</h2><p>${zh()?'点击任意日期新增课程、备课、内容工作或其他安排。':'Click any day to add a lesson, prep block, content task or other event.'}</p></div><button class="primary" onclick="openCalendarModal()">${zh()?'+ 新建日程':'+ New event'}</button></div><div class="calendar-layout"><section class="calendar-shell glass">${monthGrid()}</section><aside class="upcoming-panel glass"><div class="eyebrow">${zh()?'接下来':'UPCOMING'}</div><h3>${zh()?'未来安排':'Next events'}</h3>${next.map(e=>`<article><b>${esc2(e.title)}</b><span>${fmtDate(e.start_at)} · ${fmtTime(e.start_at)}</span><small>${studentById(e.student_id)?.name||e.event_type}</small></article>`).join('')||`<div class="empty-state compact">${zh()?'暂无安排':'Nothing scheduled'}</div>`}</aside></div>`;}

  window.openCalendarModal=function(date=''){const modal=document.getElementById('modal');modal.classList.remove('hidden');const d=date||new Date().toISOString().slice(0,10);modal.innerHTML=`<div class="modal-card glass"><div class="eyebrow cyan">${zh()?'课程日历':'COURSE CALENDAR'}</div><h2>${zh()?'新增日程':'New event'}</h2><label>${zh()?'标题':'Title'}<input id="evtTitle" placeholder="${zh()?'例如：Marcos 第6节课':'e.g. Marcos Session 6'}"></label><div class="form-grid"><label>${zh()?'学生（可选）':'Student (optional)'}<select id="evtStudent"><option value="">—</option>${(D.students||[]).map(s=>`<option value="${s.id}">${esc2(s.name)}</option>`).join('')}</select></label><label>${zh()?'类型':'Type'}<select id="evtType"><option value="lesson">${zh()?'课程':'Lesson'}</option><option value="prep">${zh()?'备课':'Prep'}</option><option value="content">${zh()?'内容':'Content'}</option><option value="admin">${zh()?'运营':'Admin'}</option><option value="other">${zh()?'其他':'Other'}</option></select></label><label>${zh()?'开始':'Start'}<input id="evtStart" type="datetime-local" value="${d}T10:00"></label><label>${zh()?'结束':'End'}<input id="evtEnd" type="datetime-local" value="${d}T11:00"></label></div><label>${zh()?'备注':'Notes'}<textarea id="evtNotes"></textarea></label><div class="modal-actions"><button class="ghost" onclick="closeModal()">${zh()?'取消':'Cancel'}</button><button class="primary" onclick="saveCalendarEvent()">${zh()?'保存日程':'Save event'}</button></div></div>`;};
  window.saveCalendarEvent=async function(){try{await ops('create_calendar_event',{title:document.getElementById('evtTitle').value,student_slug:document.getElementById('evtStudent').value||null,event_type:document.getElementById('evtType').value,start_at:new Date(document.getElementById('evtStart').value).toISOString(),end_at:document.getElementById('evtEnd').value?new Date(document.getElementById('evtEnd').value).toISOString():null,notes:document.getElementById('evtNotes').value});closeModal();await loadExt();}catch(e){alert(e.message)}};
  window.openPrepModal=function(){const modal=document.getElementById('modal');modal.classList.remove('hidden');modal.innerHTML=`<div class="modal-card glass"><div class="eyebrow cyan">${zh()?'备课中心':'LESSON PREP'}</div><h2>${zh()?'新建备课计划':'New lesson plan'}</h2><label>${zh()?'学生':'Student'}<select id="prepStudent">${(D.students||[]).map(s=>`<option value="${s.id}">${esc2(s.name)}</option>`).join('')}</select></label><div class="form-grid"><label>${zh()?'计划第几节':'Session #'}<input id="prepNo" type="number" min="1"></label><label>${zh()?'预计时间':'Scheduled for'}<input id="prepWhen" type="datetime-local"></label></div><label>${zh()?'主题':'Title'}<input id="prepTitle"></label><label>${zh()?'备课说明':'Prep notes'}<textarea id="prepNotes" placeholder="${zh()?'目标、流程、需要准备的素材、可能的分支……':'Goals, flow, materials, likely branches…'}"></textarea></label><div class="modal-actions"><button class="ghost" onclick="closeModal()">${zh()?'取消':'Cancel'}</button><button class="primary" onclick="savePrep()">${zh()?'保存备课':'Save prep'}</button></div></div>`;};
  window.savePrep=async function(){try{await ops('create_lesson_plan',{student_slug:document.getElementById('prepStudent').value,title:document.getElementById('prepTitle').value,planned_session_number:document.getElementById('prepNo').value||null,scheduled_for:document.getElementById('prepWhen').value?new Date(document.getElementById('prepWhen').value).toISOString():null,prep_notes:document.getElementById('prepNotes').value,status:'planned'});closeModal();await loadExt();}catch(e){alert(e.message)}};

  function v2Render(){const el=document.getElementById('content');if(!el)return;const old={students:window.__oldStudents,inbox:window.__oldInbox,brain:window.__oldBrain,workflows:window.__oldWorkflows,parent:window.__oldParent};const map={command,courses,prep,content:contentStudio,calendar};if(map[current])el.innerHTML=map[current]();else if(current==='students'&&typeof studentsPage==='function')el.innerHTML=studentsPage();else if(current==='inbox'&&typeof inboxPage==='function')el.innerHTML=inboxPage();else if(current==='brain'&&typeof brainPage==='function')el.innerHTML=brainPage();else if(current==='workflows'&&typeof workflowsPage==='function')el.innerHTML=workflowsPage();else if(current==='parent'&&typeof parentPage==='function')el.innerHTML=parentPage();else el.innerHTML=command();}
  window.render=v2Render;
  chrome();v2Nav();v2Render();
  window.addEventListener('load',()=>{setTimeout(loadExt,250);});
})();
